# Generated by Django 4.0.7 on 2022-09-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='to_address',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
