# Generated by Django 4.0.7 on 2022-09-15 08:26

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0002_remove_contactpage_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='pic1',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='pic2',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
    ]
