# Generated by Django 4.0.7 on 2022-09-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0003_contactpage_pic1_contactpage_pic2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='google_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='google_map',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
