# Generated by Django 4.0.7 on 2022-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0004_contactpage_address_contactpage_google_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='google_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='google_map',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
