# Generated by Django 4.0.7 on 2022-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0007_alter_contactpage_google_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='google_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
