# Generated by Django 4.0.7 on 2022-09-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0008_alter_contactpage_google_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='google_map',
        ),
    ]
