# Generated by Django 4.0.7 on 2022-09-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='youtube')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='instagram')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
