# Generated by Django 4.0.7 on 2022-08-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='youtube'),
        ),
    ]
