# Generated by Django 4.0.7 on 2022-09-20 08:36

import core.tools
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(blank=True)),
                ('about_project', wagtail.fields.RichTextField(blank=True)),
                ('client', models.CharField(blank=True, max_length=250)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('categories', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to=core.tools.file_path)),
                ('project_teaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('file', models.FileField(blank=True, upload_to=core.tools.file_path)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('page', modelcluster.fields.ParentalKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='project.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
