# Generated by Django 4.0.7 on 2022-09-20 09:51

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='file',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
    ]
