# Generated by Django 4.0.7 on 2022-08-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='pic1',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='pic2',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='pic3',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='pic4',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
    ]
