# Generated by Django 4.0.7 on 2022-08-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectpage_pic1_projectpage_pic2_projectpage_pic3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Project Page'},
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='pic4',
        ),
    ]
