# Generated by Django 4.0.7 on 2022-09-20 10:09

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('project', '0003_projectpagetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='project.ProjectPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
