# Generated by Django 4.0.7 on 2022-08-09 17:46

import company.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=250, verbose_name='')),
                ('regnum', models.CharField(max_length=20, verbose_name='')),
                ('description', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='About company text')),
                ('logo', models.ImageField(blank=True, default='company/user-default.png', null=True, upload_to=company.models.get_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
