# Generated by Django 4.0.7 on 2022-09-15 09:54

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('text', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='youtube')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='instagram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
