# Generated by Django 4.0.7 on 2022-08-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('caption', models.CharField(max_length=200)),
                ('text_about', models.TextField(blank=True, verbose_name='About text')),
                ('pic1', models.FileField(blank=True, upload_to='pictures/')),
                ('pic2', models.FileField(blank=True, upload_to='pictures/')),
                ('pic3', models.FileField(blank=True, upload_to='pictures/')),
                ('pic4', models.FileField(blank=True, upload_to='pictures/')),
                ('pic5', models.FileField(blank=True, upload_to='pictures/')),
                ('pic6', models.FileField(blank=True, upload_to='pictures/')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
