# Generated by Django 4.0.7 on 2022-09-15 07:34

import core.tools
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aboutsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='pic1',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pic2',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pic3',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pic4',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pic5',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pic6',
            field=models.FileField(blank=True, upload_to=core.tools.file_path),
        ),
        migrations.CreateModel(
            name='AboutPageRelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='aboutsite.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
